development:
  adapter: postgis
  encoding: unicode
  postgis_extension: true
  schema_search_path: public,postgis
  pool: 5
  host: localhost
  database: uk_postcodes_development    # substitute your dev database name
  username: root                # substitute the username your app will use to connect
  password:                             # substitute the user's password
  su_username: root                     # substitute a superuser for the database
  su_password:                          # substitute the superuser's password

test: &test
  adapter: postgis
  encoding: unicode
  postgis_extension: true
  schema_search_path: public,postgis
  pool: 5
  host: localhost
  database: uk_postcodes_test      # substitute your dev database name
  username: postgres               # substitute the username your app will use to connect
  password:                        # substitute the user's password
  su_username: root                # substitute a superuser for the database
  su_password:                     # substitute the superuser's password

production:
  adapter: postgis
  encoding: unicode
  postgis_extension: true
  schema_search_path: public,postgis
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: uk_postcodes_production   # substitute your dev database name
  username: uk_postcodes     # substitute the username your app will use to connect
  password: <%= ENV['DATABASE_PASSWORD'] %>     # substitute the user's password
  su_username: <%= ENV['SU_USERNAME'] %>  # substitute a superuser for the database
  su_password: <%= ENV['SU_PASSWORD'] %>  # substitute the superuser's password

cucumber:
  <<: *test
